build:
	xcodebuild -workspace BitskiUnitySDK.xcworkspace -configuration Release -scheme BitskiUnitySDKFatFramework CONFIGURATION_BUILD_DIR=$(PWD)/build
clean:
	xcodebuild -workspace BitskiUnitySDK.xcworkspace -configuration Release -scheme BitskiUnitySDKFatFramework clean CONFIGURATION_BUILD_DIR=$(PWD)/build
	rm -rf build
